# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Bruno Amaral F
title: Senior Site Reliability Engineer
email: brunoamaralf@gmail.com
#website: 

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  bamaralf
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: bamaralf
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
      Hi! I am a SRE/DevOps Engineer who assisted several projects with DevOps culture and automation adoption.
      These are some tasks I worked on previous projects:
      - designing cloud and on-premises infrastructures
      - developing robust CI/CD workflows
      - profiling applications for optimal scalability
      - setting up monitoring tools and alerts
      - managing Kubernetes Container Clusters in multi-cloud providers and on-premises bare-metal
      - developing Terraform modules
      - developing Helm charts
      - migrating infrastructure to cloud providers
      - git repositories management
      - databases operations
      - managing required infrastructure for blockchain nodes
      - implementing ETL workflows for machine learning.

content:
  - title: Open Source Contributions # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: terraform-aws-s3-bucket
        link: https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/commits?author=bamaralf
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A Terraform module for provisioning AWS S3 buckets.
        # description: | # this will include new lines to allow paragraphs
        #   A Terraform module for provisioning AWS S3 buckets.

      - layout: top-middle
        title: terraform-azurerm-aks
        link: https://github.com/Azure/terraform-azurerm-aks/commits?author=bamaralf
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A Terraform module for provisioning AKS clusters (Kubernetes).
        # description: | # this will include new lines to allow paragraphs
        #  A Terraform module for provisioning AKS clusters (Kubernetes).

      - layout: top-middle
        title: terraform-azurerm-vnetpeering
        link: https://github.com/Azure/terraform-azurerm-vnetpeering/pull/9
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A Terraform module for provisioning Azure VNET Peering connections.
        # description: | # this will include new lines to allow paragraphs
        #   A Terraform module for provisioning Azure VNET Peering connections.

      - layout: top-middle
        title: terraform-azurerm-vnet
        link: https://github.com/Azure/terraform-azurerm-vnet/commits?author=bamaralf
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A Terraform module for provisioning Azure VNETs.
        # description: | # this will include new lines to allow paragraphs
        #   A Terraform module for provisioning Azure VNETs.

      - layout: top-middle
        title: terraspace_plugin_azurerm
        link: https://github.com/boltops-tools/terraspace_plugin_azurerm/pull/8
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Terraspace is a Terraform framework.
        # description: | # this will include new lines to allow paragraphs
        #   Terraspace is a Terraform framework.

      - layout: top-middle
        title: axonserver Helm chart
        link: https://github.com/trustd-solutions/helm-charts/tree/master/charts/axonserver
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A Helm chart for provisioning Axonserver clusters running in Kubernetes (https://developer.axoniq.io/axon-server/overview).
        # description: | # this will include new lines to allow paragraphs
        #   A Helm chart for provisioning Axonserver clusters running in Kubernetes (https://developer.axoniq.io/axon-server/overview).

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Betterwise
        link: https://betterwise.com
        # link_text: boringcompany.com
        sub_title: Senior Site Reliability Engineer 
        caption: November, 2022 - Present
        quote: >
          Maintaining the continuous integration and continuous delivery workflows.
          Maintaining production environments.
          Setting up monitoring and alerting tools for production environments.
          Setting up auto-scalable infrastructures.
          Optimizing the use of Cloud resources.
          Implementing Terraform modules.
          Developing Helm charts.
        predominant stack: | # this will include new lines to allow paragraphs
          - Kotlin
          - Axonserver/Axon Framework (https://www.axoniq.io/)
          - Terraform
          - Github Actions
          - Kubernetes
          - Helm
          - AWS
          - Datadog

      - layout: left
        title: Aetion
        link: https://aetion.com
        # link_text: boringcompany.com
        sub_title: Senior Site Reliability Engineer 
        caption: Mar, 2021 - October, 2022
        quote: >
          Maintaining the continuous integration and continuous delivery workflows.
          Maintaining production environments.
          Setting up monitoring and alerting tools for production environments.
          Setting up auto-scalable infrastructures.
          Optimizing the use of Cloud resources.
          Implementing Terraform modules.
          Developing Helm charts.
          Developing ETL workflows with AWS Glue
        predominant stack: | # this will include new lines to allow paragraphs
          - Terraform
          - Github Actions
          - Jenkins
          - Kubernetes
          - Helm
          - Datadog
          - Databricks
          - AWS Redshift
          - AWS Glue

      - layout: left
        title: Codeminer42
        link: https://codeminer42.com
        # link_text: boringcompany.com
        sub_title: Senior Site Reliability Engineer 
        caption: May,2018 - Mar,2021
        quote: >
          Maintaining the continuous integration and continuous delivery workflows.
          Designing and implementing a crypto exchange cloud infrastructure.
          Maintaining production environments.
          Setting up monitoring and alerting tools for production environments.
          Setting up auto-scalable infrastructures.
          Optimizing the use of Cloud resources.
          Implementing Terraform modules.
          Migrating production platforms to Kubernetes clusters while maintaining their availability.
          Developing Helm charts.
          Applying changes to customers environments providing scalability for traffic load change
          Profiling apps and running automated load tests
        predominant stack: | # this will include new lines to allow paragraphs
          - Java
          - Golang
          - Ruby
          - Elixir
          - Terraform
          - Ansible
          - Gitlab-CI
          - SemaphoreCI
          - Kubernetes
          - Helm
          - Prometheus
          - Grafana
          - GCP Stackdriver
          - Blockchain infrastructure
          - AWS
          - GCP
          - Azure

      - layout: left
        title: Cloudwalk Payments
        link: https://cloudwalk.io
        # link_text: boringcompany.com
        sub_title: Backend Engineer 
        caption: Ju, 2017- Jun, 2018
        quote: >
          Developing core platform features.        
          Developing Ruby/Sinatra API to interact with the company's VPNs status information.
          Maintaining the continuous integration and continuous delivery workflows.
          Setting up monitoring and alerting tools.
          Developing Ansible playbooks
          Migrating the production environment to an auto-scalable infrastructure on Kubernetes (AWS).
          Optimizing the use of AWS resources by reducing its costs and improving the overall performance.
          Maintaining the PCI DSS security compliance by implementing its requirements through an Infrastructure as Code paradigm.
        predominant stack: | # this will include new lines to allow paragraphs
          - Golang
          - Ruby
          - Terraform
          - Ansible
          - JenkinsCI
          - Kubernetes, KOPS
          - AWS, GCP
          - PCI DSS 
          - Blockchain infrastructure

      - layout: left
        title: Ifactory/Opentext
        link: https://www.opentext.com/ 
        # link_text: boringcompany.com
        sub_title: Devops Engineer 
        caption: Jul, 2014 - Jun, 2017
        quote: >
          Implementing application deployment workflows, such as Canary Deployments, Blue/Green Deployments and Rolling Upgrades.
          Applying configuration management with Ansible.
          Implementing Terraform modules.
          Working with internal and external teams.
        predominant stack: | # this will include new lines to allow paragraphs
          - Java
          - Middleware Support (Tomcat, Weblogic, Websphere)
          - Ansible, Chef
          - Jmeter
          - JenkinsCI
          - Terrform
          - Kubernetes
          - AWS
          - WSO2 tools

      - layout: left
        title: Dell
        link: http://projetolead.com.br/index.php
        # link_text: boringcompany.com
        sub_title: Infrastructure/Network Consultant
        caption: Jan, 2014 - Jul, 2014
        quote: >
          Maintaining the Firewall/Proxy systems.
          Implementing the inventory management system.
          Migrating the bare-metal infrastructure to a Cloud provider.
        predominant stack: | # this will include new lines to allow paragraphs
          - Java
          - AWS
          - Networking
          - Monitoring

  # - title: Education # Title for the section
  #   - layout: list # Type of content section (list/text)
  #     content:
  #       - layout: left
  #         title: Universidade Federal do Ceara 
  #         caption: 2013 - 2018
  #         sub_title: Computer Engineering, BSc
  #       # quote: >
  #       #   ""
  #       # description: | # this will include new lines to allow paragraphs
  #       #   ""

  - title: Frequent Stack
    layout: text
    content: | # this will include new lines to allow paragraphs
      Containers:
      - Docker
      - Kubernetes
      
      Cloud Providers:
      - AWS
      - GCP
      - Azure
      
      Infrastrucuture as a code:
      - Terraform
      
      Configuration management:
      - Ansible
      
      Scripting languages:
      - Bash
      - Ruby
      - Python

      Programming languages from previously supported platforms:
      - PHP
      - Ruby
      - NodeJs
      - Golang
      - C
      - Java
      - Kotlin

      Relational Database operations:
      - MySQL
      - Postgres
      - MSSQL
      
      Monitoring tools:
      - Prometheus
      - Grafana
      - Datadog

#      Look at this cool image  
#      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
